/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xscdxjurbgcrfkjlvdfb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzY2R4anVyYmdjcmZramx2ZGZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgyNzc4OTYsImV4cCI6MjA4Mzg1Mzg5Nn0.1zq7gw6Ep3-OsgRJXkEp2ow-xw9xD-maJIHuyHyIIWs"